[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.dev]
command = "cargo"
args = ["run", "--", "--docker-host", "/run/nanocl/docker.sock"]

[tasks.cov]
command = "cargo"
args = ["llvm-cov", "nextest", "--", "--output-path", "./daemon_cov.json", "--json"]

[tasks.test]
command = "cargo"
args = ["nextest", "run"]

[tasks.test-debug]
command = "cargo"
args = ["test", "--", "--nocapture"]

[tasks.release]
command = "cargo"
args = ["build", "--release"]
